AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - app/assets/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/tasks/auto_annotate_models.rake
    - log/**/*
    - spec/**/*
    - vendor/**/*
    - Gemfile
    - Capfile
    - script/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/AndOr:
  EnforcedStyle: conditionals

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 25
