version: "3.7"

services:
  s3pullbackups:
    build:
      context: ../
      target: runtime
      args:
        APPUID: ${APPUID}
        APPGID: ${APPGID}
    command: bash -c "bundle exec ./s3_pull_backups.rb"
    container_name: "s3pullbackups"
    volumes:
      - ../:/s3pullbackups
      - s3pullbackups_bundle:/s3pullbackups/vendor/bundle
    env_file: ../.env

  s3pullbackups_bundle:
    image: busybox
    container_name: "s3pullbackups_bundle"
    volumes:
      - s3pullbackups_bundle:/s3pullbackups/vendor/bundle

volumes:
  s3pullbackups_bundle:
